repro.db.tenant_a.db-kind=oracle
repro.db.tenant_a.username=
repro.db.tenant_a.password=
repro.db.tenant_a.url=

repro.flyway.business.enabled=false
repro.flyway.patch.enabled=false
repro.flyway.cutover-version=20260325.0000.00


quarkus.datasource.tenant_a.db-kind=${repro.db.tenant_a.db-kind}
quarkus.datasource.tenant_a.username=${repro.db.tenant_a.username}
quarkus.datasource.tenant_a.password=${repro.db.tenant_a.password}
quarkus.datasource.tenant_a.jdbc.url=${repro.db.tenant_a.url}
quarkus.datasource.tenant_a.jdbc=false
